package model

type InterestScores struct {
	NewsScore      int16
	PoliticsScore int16
	EconomicsScore int16
	HealthScore int16
	SportsScore int16
	EntertainmentScore int16
	ArtScore int16
	CookingScore int16
	TravelScore int16
	FashionScore int16
	BeautyScore int16
	PetsScore int16
	ParentingScore int16
	EducationScore int16
	EnvironmentScore int16
	ClimateScore int16
	SpaceScore int16
	MentalHealthScore int16
	FitnessScore int16
	ReadingScore int16
	HistoryScore int16
	PhilosophyScore int16
	ReligionScore int16
	CultureScore int16
	VolunteeringScore int16
	SocialIssuesScore int16
	LawScore int16
	TaxesScore int16
	InvestmentScore int16
	RealEstateScore int16
	DIYScore int16
	GardeningScore int16
	InteriorDesignScore int16
	AutomotiveScore int16
	GamingScore int16
	AnimeMangaScore int16
	CreativeWorksScore int16
	PhotographyVideoScore int16
	MediaScore int16
	MarketingScore int16
	BrandingScore int16
	EntrepreneurshipScore int16
	RemoteWorkScore int16
	DataScienceScore int16
	IoTScore int16
	RoboticsEngineeringScore int16
	BiotechnologyScore int16
	NanotechnologyScore int16
	EnergyTechnologyScore int16
	ArchaeologyScore int16
	PsychologyScore int16
	SociologyScore int16
	AnthropologyScore int16
	GeographyScore int16
	GeologyScore int16
	MeteorologyScore int16
	DisasterEmergencyManagementScore int16
	UrbanPlanningScore int16
	ArchitectureScore int16
	AgricultureScore int16
	NutritionScienceScore int16
	SleepScienceScore int16
	ProductivityScore int16
	LeadershipScore int16
	InternationalRelationsScore int16
	FuturePredictionsScore int16
	EventsScore int16
	CommunityScore int16
	TrendsScore int16
	LifestyleScore int16
	SoftwareDevelopmentScore int16
	ProgrammingLanguagesScore int16
	WebDevelopmentScore int16
	MobileAppDevelopmentScore int16
	DebuggingTechniquesScore int16
	AlgorithmsMathematicsScore int16
	DatabaseDesignScore int16
	CloudComputingScore int16
	ServerManagementScore int16
	NetworkSecurityScore int16
	CryptographyScore int16
	ArtificialIntelligenceScore int16
	MachineLearningScore int16
	DeepLearningScore int16
	ComputerVisionScore int16
	NaturalLanguageProcessingScore int16
	BlockchainTechnologyScore int16
	QuantumComputingScore int16
	EdgeComputingScore int16
	MicroservicesArchitectureScore int16
	DevOpsScore int16
	ContainerTechnologyScore int16
	CICDScore int16
	TestAutomationScore int16
	UXUIDesignScore int16
	AgileDevelopmentMethodologiesScore int16
	OpenSourceScore int16
	VersionControlScore int16
	APIDesignScore int16
	PerformanceOptimizationScore int16
}

func (i *InterestScores) GetScore(label *Label) int16 {
	if label == nil {
		return 0
	}

	switch *label {
	case LabelNews:
		return i.NewsScore
	case LabelPolitics:
		return i.PoliticsScore
	case LabelEconomics:
		return i.EconomicsScore
	case LabelHealth:
		return i.HealthScore
	case LabelSports:
		return i.SportsScore
	case LabelEntertainment:
		return i.EntertainmentScore
	case LabelArt:
		return i.ArtScore
	case LabelCooking:
		return i.CookingScore
	case LabelTravel:
		return i.TravelScore
	case LabelFashion:
		return i.FashionScore
	case LabelBeauty:
		return i.BeautyScore
	case LabelPets:
		return i.PetsScore
	case LabelParenting:
		return i.ParentingScore
	case LabelEducation:
		return i.EducationScore
	case LabelEnvironment:
		return i.EnvironmentScore
	case LabelClimate:
		return i.ClimateScore
	case LabelSpace:
		return i.SpaceScore
	case LabelMentalHealth:
		return i.MentalHealthScore
	case LabelFitness:
		return i.FitnessScore
	case LabelReading:
		return i.ReadingScore
	case LabelHistory:
		return i.HistoryScore
	case LabelPhilosophy:
		return i.PhilosophyScore
	case LabelReligion:
		return i.ReligionScore
	case LabelCulture:
		return i.CultureScore
	case LabelVolunteering:
		return i.VolunteeringScore
	case LabelSocialIssues:
		return i.SocialIssuesScore
	case LabelLaw:
		return i.LawScore
	case LabelTaxes:
		return i.TaxesScore
	case LabelInvestment:
		return i.InvestmentScore
	case LabelRealEstate:
		return i.RealEstateScore
	case LabelDIY:
		return i.DIYScore
	case LabelGardening:
		return i.GardeningScore
	case LabelInteriorDesign:
		return i.InteriorDesignScore
	case LabelAutomotive:
		return i.AutomotiveScore
	case LabelGaming:
		return i.GamingScore
	case LabelAnimeManga:
		return i.AnimeMangaScore
	case LabelCreativeWorks:
		return i.CreativeWorksScore
	case LabelPhotographyVideo:
		return i.PhotographyVideoScore
	case LabelMedia:
		return i.MediaScore
	case LabelMarketing:
		return i.MarketingScore
	case LabelBranding:
		return i.BrandingScore
	case LabelEntrepreneurship:
		return i.EntrepreneurshipScore
	case LabelRemoteWork:
		return i.RemoteWorkScore
	case LabelDataScience:
		return i.DataScienceScore
	case LabelIoT:
		return i.IoTScore
	case LabelRoboticsEngineering:
		return i.RoboticsEngineeringScore
	case LabelBiotechnology:
		return i.BiotechnologyScore
	case LabelNanotechnology:
		return i.NanotechnologyScore
	case LabelEnergyTechnology:
		return i.EnergyTechnologyScore
	case LabelArchaeology:
		return i.ArchaeologyScore
	case LabelPsychology:
		return i.PsychologyScore
	case LabelSociology:
		return i.SociologyScore
	case LabelAnthropology:
		return i.AnthropologyScore
	case LabelGeography:
		return i.GeographyScore
	case LabelGeology:
		return i.GeologyScore
	case LabelMeteorology:
		return i.MeteorologyScore
	case LabelDisasterEmergencyManagement:
		return i.DisasterEmergencyManagementScore
	case LabelUrbanPlanning:
		return i.UrbanPlanningScore
	case LabelArchitecture:
		return i.ArchitectureScore
	case LabelAgriculture:
		return i.AgricultureScore
	case LabelNutritionScience:
		return i.NutritionScienceScore
	case LabelSleepScience:
		return i.SleepScienceScore
	case LabelProductivity:
		return i.ProductivityScore
	case LabelLeadership:
		return i.LeadershipScore
	case LabelInternationalRelations:
		return i.InternationalRelationsScore
	case LabelFuturePredictions:
		return i.FuturePredictionsScore
	case LabelEvents:
		return i.EventsScore
	case LabelCommunity:
		return i.CommunityScore
	case LabelTrends:
		return i.TrendsScore
	case LabelLifestyle:
		return i.LifestyleScore
	case LabelSoftwareDevelopment:
		return i.SoftwareDevelopmentScore
	case LabelProgrammingLanguages:
		return i.ProgrammingLanguagesScore
	case LabelWebDevelopment:
		return i.WebDevelopmentScore
	case LabelMobileAppDevelopment:
		return i.MobileAppDevelopmentScore
	case LabelDebuggingTechniques:
		return i.DebuggingTechniquesScore
	case LabelAlgorithmsMathematics:
		return i.AlgorithmsMathematicsScore
	case LabelDatabaseDesign:
		return i.DatabaseDesignScore
	case LabelCloudComputing:
		return i.CloudComputingScore
	case LabelServerManagement:
		return i.ServerManagementScore
	case LabelNetworkSecurity:
		return i.NetworkSecurityScore
	case LabelCryptography:
		return i.CryptographyScore
	case LabelArtificialIntelligence:
		return i.ArtificialIntelligenceScore
	case LabelMachineLearning:
		return i.MachineLearningScore
	case LabelDeepLearning:
		return i.DeepLearningScore
	case LabelComputerVision:
		return i.ComputerVisionScore
	case LabelNaturalLanguageProcessing:
		return i.NaturalLanguageProcessingScore
	case LabelBlockchainTechnology:
		return i.BlockchainTechnologyScore
	case LabelQuantumComputing:
		return i.QuantumComputingScore
	case LabelEdgeComputing:
		return i.EdgeComputingScore
	case LabelMicroservicesArchitecture:
		return i.MicroservicesArchitectureScore
	case LabelDevOps:
		return i.DevOpsScore
	case LabelContainerTechnology:
		return i.ContainerTechnologyScore
	case LabelCICD:
		return i.CICDScore
	case LabelTestAutomation:
		return i.TestAutomationScore
	case LabelUXUIDesign:
		return i.UXUIDesignScore
	case LabelAgileDevelopmentMethodologies:
		return i.AgileDevelopmentMethodologiesScore
	case LabelOpenSource:
		return i.OpenSourceScore
	case LabelVersionControl:
		return i.VersionControlScore
	case LabelAPIDesign:
		return i.APIDesignScore
	case LabelPerformanceOptimization:
		return i.PerformanceOptimizationScore
	default:
		return 0
	}
}