openapi: 3.0.0
info:
    title: Message Management API
    version: 1.0.0
    description: API for managing user messages

paths:
    /conversations/{user_id}/messages:
        get:
            summary: Get messages of a user
            operationId: GetMessages
            parameters:
                - name: user_id
                  in: path
                  required: true
                  schema:
                      type: string
                - name: limit
                  in: query
                  schema:
                      type: integer
                      format: int32
                  required: true
                - name: offset
                  in: query
                  schema:
                      type: integer
                      format: int32
                  required: true
            responses:
                "200":
                    description: Messages retrieved successfully
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/MessageResponses"
                "400":
                    description: Bad request
                "500":
                    description: Internal server error
        post:
            summary: Send a message to a user
            operationId: SendMessage
            parameters:
                - name: user_id
                  in: path
                  required: true
                  schema:
                      type: string
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/MessageRequest"
            responses:
                "200":
                    description: Message sent successfully
                "400":
                    description: Bad request
                "500":
                    description: Internal server error
    /conversations/{user_id}/messages/read:
        patch:
            summary: Mark messages as read
            operationId: MarkMessagesAsRead
            parameters:
                - name: user_id
                  in: path
                  required: true
                  schema:
                      type: string
            responses:
                "200":
                    description: Messages marked as read successfully
                "400":
                    description: Bad request
                "500":
                    description: Internal server error

components:
    schemas:
        MessageRequest:
            type: object
            required:
                - content
            properties:
                content:
                    type: string
        MessageResponse:
            type: object
            required:
                - sender_account_id
                - content
                - is_read
                - created_at
            properties:
                sender_account_id:
                    type: string
                content:
                    type: string
                is_read:
                    type: boolean
                created_at:
                    type: string
                    format: date-time
        MessageResponses:
            type: array
            items:
                $ref: "#/components/schemas/MessageResponse"
