version: "3.8"

services:
    kaizen_db:
        container_name: kaizen_db
        build:
            context: .
            dockerfile: Dockerfile
        platform: linux/x86_64
        tty: true
        ports:
            - "3306:3306"
        env_file:
            - ../.env
        volumes:
            - type: volume
              source: kaizen_mysql_2
              target: /var/lib/mysql
            - type: bind
              source: ./init
              target: /docker-entrypoint-initdb.d

volumes:
    kaizen_mysql_2:
        name: kaizen_mysql_2
