// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlcgen

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type FollowStatus string

const (
	FollowStatusPending  FollowStatus = "pending"
	FollowStatusAccepted FollowStatus = "accepted"
)

func (e *FollowStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FollowStatus(s)
	case string:
		*e = FollowStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for FollowStatus: %T", src)
	}
	return nil
}

type NullFollowStatus struct {
	FollowStatus FollowStatus
	Valid        bool // Valid is true if FollowStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFollowStatus) Scan(value interface{}) error {
	if value == nil {
		ns.FollowStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FollowStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFollowStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FollowStatus), nil
}

type NotificationType string

const (
	NotificationTypeFollow          NotificationType = "follow"
	NotificationTypeLike            NotificationType = "like"
	NotificationTypeRetweet         NotificationType = "retweet"
	NotificationTypeReply           NotificationType = "reply"
	NotificationTypeMessage         NotificationType = "message"
	NotificationTypeQuote           NotificationType = "quote"
	NotificationTypeFollowRequest   NotificationType = "follow_request"
	NotificationTypeRequestAccepted NotificationType = "request_accepted"
	NotificationTypeReport          NotificationType = "report"
	NotificationTypeWarning         NotificationType = "warning"
	NotificationTypeOther           NotificationType = "other"
)

func (e *NotificationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationType(s)
	case string:
		*e = NotificationType(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationType: %T", src)
	}
	return nil
}

type NullNotificationType struct {
	NotificationType NotificationType
	Valid            bool // Valid is true if NotificationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationType) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationType), nil
}

type ReportReason string

const (
	ReportReasonSpam                 ReportReason = "spam"
	ReportReasonHarassment           ReportReason = "harassment"
	ReportReasonInappropriateContent ReportReason = "inappropriate_content"
	ReportReasonOther                ReportReason = "other"
)

func (e *ReportReason) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReportReason(s)
	case string:
		*e = ReportReason(s)
	default:
		return fmt.Errorf("unsupported scan type for ReportReason: %T", src)
	}
	return nil
}

type NullReportReason struct {
	ReportReason ReportReason
	Valid        bool // Valid is true if ReportReason is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReportReason) Scan(value interface{}) error {
	if value == nil {
		ns.ReportReason, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReportReason.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReportReason) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReportReason), nil
}

type TweetLabel string

const (
	TweetLabelNews                          TweetLabel = "news"
	TweetLabelPolitics                      TweetLabel = "politics"
	TweetLabelEconomics                     TweetLabel = "economics"
	TweetLabelHealth                        TweetLabel = "health"
	TweetLabelSports                        TweetLabel = "sports"
	TweetLabelEntertainment                 TweetLabel = "entertainment"
	TweetLabelArt                           TweetLabel = "art"
	TweetLabelCooking                       TweetLabel = "cooking"
	TweetLabelTravel                        TweetLabel = "travel"
	TweetLabelFashion                       TweetLabel = "fashion"
	TweetLabelBeauty                        TweetLabel = "beauty"
	TweetLabelPets                          TweetLabel = "pets"
	TweetLabelParenting                     TweetLabel = "parenting"
	TweetLabelEducation                     TweetLabel = "education"
	TweetLabelEnvironment                   TweetLabel = "environment"
	TweetLabelClimate                       TweetLabel = "climate"
	TweetLabelSpace                         TweetLabel = "space"
	TweetLabelMentalHealth                  TweetLabel = "mental_health"
	TweetLabelFitness                       TweetLabel = "fitness"
	TweetLabelReading                       TweetLabel = "reading"
	TweetLabelHistory                       TweetLabel = "history"
	TweetLabelPhilosophy                    TweetLabel = "philosophy"
	TweetLabelReligion                      TweetLabel = "religion"
	TweetLabelCulture                       TweetLabel = "culture"
	TweetLabelVolunteering                  TweetLabel = "volunteering"
	TweetLabelSocialIssues                  TweetLabel = "social_issues"
	TweetLabelLaw                           TweetLabel = "law"
	TweetLabelTaxes                         TweetLabel = "taxes"
	TweetLabelInvestment                    TweetLabel = "investment"
	TweetLabelRealEstate                    TweetLabel = "real_estate"
	TweetLabelDiy                           TweetLabel = "diy"
	TweetLabelGardening                     TweetLabel = "gardening"
	TweetLabelInteriorDesign                TweetLabel = "interior_design"
	TweetLabelAutomotive                    TweetLabel = "automotive"
	TweetLabelGaming                        TweetLabel = "gaming"
	TweetLabelAnimeManga                    TweetLabel = "anime_manga"
	TweetLabelCreativeWorks                 TweetLabel = "creative_works"
	TweetLabelPhotographyVideo              TweetLabel = "photography_video"
	TweetLabelMedia                         TweetLabel = "media"
	TweetLabelMarketing                     TweetLabel = "marketing"
	TweetLabelBranding                      TweetLabel = "branding"
	TweetLabelEntrepreneurship              TweetLabel = "entrepreneurship"
	TweetLabelRemoteWork                    TweetLabel = "remote_work"
	TweetLabelDataScience                   TweetLabel = "data_science"
	TweetLabelIot                           TweetLabel = "iot"
	TweetLabelRoboticsEngineering           TweetLabel = "robotics_engineering"
	TweetLabelBiotechnology                 TweetLabel = "biotechnology"
	TweetLabelNanotechnology                TweetLabel = "nanotechnology"
	TweetLabelEnergyTechnology              TweetLabel = "energy_technology"
	TweetLabelArchaeology                   TweetLabel = "archaeology"
	TweetLabelPsychology                    TweetLabel = "psychology"
	TweetLabelSociology                     TweetLabel = "sociology"
	TweetLabelAnthropology                  TweetLabel = "anthropology"
	TweetLabelGeography                     TweetLabel = "geography"
	TweetLabelGeology                       TweetLabel = "geology"
	TweetLabelMeteorology                   TweetLabel = "meteorology"
	TweetLabelDisasterEmergencyManagement   TweetLabel = "disaster_emergency_management"
	TweetLabelUrbanPlanning                 TweetLabel = "urban_planning"
	TweetLabelArchitecture                  TweetLabel = "architecture"
	TweetLabelAgriculture                   TweetLabel = "agriculture"
	TweetLabelNutritionScience              TweetLabel = "nutrition_science"
	TweetLabelSleepScience                  TweetLabel = "sleep_science"
	TweetLabelProductivity                  TweetLabel = "productivity"
	TweetLabelLeadership                    TweetLabel = "leadership"
	TweetLabelInternationalRelations        TweetLabel = "international_relations"
	TweetLabelFuturePredictions             TweetLabel = "future_predictions"
	TweetLabelEvents                        TweetLabel = "events"
	TweetLabelCommunity                     TweetLabel = "community"
	TweetLabelTrends                        TweetLabel = "trends"
	TweetLabelLifestyle                     TweetLabel = "lifestyle"
	TweetLabelSoftwareDevelopment           TweetLabel = "software_development"
	TweetLabelProgrammingLanguages          TweetLabel = "programming_languages"
	TweetLabelWebDevelopment                TweetLabel = "web_development"
	TweetLabelMobileAppDevelopment          TweetLabel = "mobile_app_development"
	TweetLabelDebuggingTechniques           TweetLabel = "debugging_techniques"
	TweetLabelAlgorithmsMathematics         TweetLabel = "algorithms_mathematics"
	TweetLabelDatabaseDesign                TweetLabel = "database_design"
	TweetLabelCloudComputing                TweetLabel = "cloud_computing"
	TweetLabelServerManagement              TweetLabel = "server_management"
	TweetLabelNetworkSecurity               TweetLabel = "network_security"
	TweetLabelCryptography                  TweetLabel = "cryptography"
	TweetLabelArtificialIntelligence        TweetLabel = "artificial_intelligence"
	TweetLabelMachineLearning               TweetLabel = "machine_learning"
	TweetLabelDeepLearning                  TweetLabel = "deep_learning"
	TweetLabelComputerVision                TweetLabel = "computer_vision"
	TweetLabelNaturalLanguageProcessing     TweetLabel = "natural_language_processing"
	TweetLabelBlockchainTechnology          TweetLabel = "blockchain_technology"
	TweetLabelQuantumComputing              TweetLabel = "quantum_computing"
	TweetLabelEdgeComputing                 TweetLabel = "edge_computing"
	TweetLabelMicroservicesArchitecture     TweetLabel = "microservices_architecture"
	TweetLabelDevops                        TweetLabel = "devops"
	TweetLabelContainerTechnology           TweetLabel = "container_technology"
	TweetLabelCiCd                          TweetLabel = "ci_cd"
	TweetLabelTestAutomation                TweetLabel = "test_automation"
	TweetLabelUxUiDesign                    TweetLabel = "ux_ui_design"
	TweetLabelAgileDevelopmentMethodologies TweetLabel = "agile_development_methodologies"
	TweetLabelOpenSource                    TweetLabel = "open_source"
	TweetLabelVersionControl                TweetLabel = "version_control"
	TweetLabelApiDesign                     TweetLabel = "api_design"
	TweetLabelPerformanceOptimization       TweetLabel = "performance_optimization"
)

func (e *TweetLabel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TweetLabel(s)
	case string:
		*e = TweetLabel(s)
	default:
		return fmt.Errorf("unsupported scan type for TweetLabel: %T", src)
	}
	return nil
}

type NullTweetLabel struct {
	TweetLabel TweetLabel
	Valid      bool // Valid is true if TweetLabel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTweetLabel) Scan(value interface{}) error {
	if value == nil {
		ns.TweetLabel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TweetLabel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTweetLabel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TweetLabel), nil
}

type Account struct {
	ID          string
	UserID      string
	UserName    string
	IsSuspended bool
	IsAdmin     bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Block struct {
	BlockerAccountID string
	BlockedAccountID string
	CreatedAt        time.Time
}

type Conversation struct {
	ID              int64
	Account1ID      string
	Account2ID      string
	LastMessageID   sql.NullInt64
	LastMessageTime time.Time
}

type Follow struct {
	FollowerAccountID  string
	FollowingAccountID string
	Status             FollowStatus
	CreatedAt          time.Time
}

type Hashtag struct {
	ID        int64
	Tag       string
	CreatedAt time.Time
}

type Interest struct {
	AccountID                          string
	NewsScore                          sql.NullInt16
	PoliticsScore                      sql.NullInt16
	EconomicsScore                     sql.NullInt16
	HealthScore                        sql.NullInt16
	SportsScore                        sql.NullInt16
	EntertainmentScore                 sql.NullInt16
	ArtScore                           sql.NullInt16
	CookingScore                       sql.NullInt16
	TravelScore                        sql.NullInt16
	FashionScore                       sql.NullInt16
	BeautyScore                        sql.NullInt16
	PetsScore                          sql.NullInt16
	ParentingScore                     sql.NullInt16
	EducationScore                     sql.NullInt16
	EnvironmentScore                   sql.NullInt16
	ClimateScore                       sql.NullInt16
	SpaceScore                         sql.NullInt16
	MentalHealthScore                  sql.NullInt16
	FitnessScore                       sql.NullInt16
	ReadingScore                       sql.NullInt16
	HistoryScore                       sql.NullInt16
	PhilosophyScore                    sql.NullInt16
	ReligionScore                      sql.NullInt16
	CultureScore                       sql.NullInt16
	VolunteeringScore                  sql.NullInt16
	SocialIssuesScore                  sql.NullInt16
	LawScore                           sql.NullInt16
	TaxesScore                         sql.NullInt16
	InvestmentScore                    sql.NullInt16
	RealEstateScore                    sql.NullInt16
	DiyScore                           sql.NullInt16
	GardeningScore                     sql.NullInt16
	InteriorDesignScore                sql.NullInt16
	AutomotiveScore                    sql.NullInt16
	GamingScore                        sql.NullInt16
	AnimeMangaScore                    sql.NullInt16
	CreativeWorksScore                 sql.NullInt16
	PhotographyVideoScore              sql.NullInt16
	MediaScore                         sql.NullInt16
	MarketingScore                     sql.NullInt16
	BrandingScore                      sql.NullInt16
	EntrepreneurshipScore              sql.NullInt16
	RemoteWorkScore                    sql.NullInt16
	DataScienceScore                   sql.NullInt16
	IotScore                           sql.NullInt16
	RoboticsEngineeringScore           sql.NullInt16
	BiotechnologyScore                 sql.NullInt16
	NanotechnologyScore                sql.NullInt16
	EnergyTechnologyScore              sql.NullInt16
	ArchaeologyScore                   sql.NullInt16
	PsychologyScore                    sql.NullInt16
	SociologyScore                     sql.NullInt16
	AnthropologyScore                  sql.NullInt16
	GeographyScore                     sql.NullInt16
	GeologyScore                       sql.NullInt16
	MeteorologyScore                   sql.NullInt16
	DisasterEmergencyManagementScore   sql.NullInt16
	UrbanPlanningScore                 sql.NullInt16
	ArchitectureScore                  sql.NullInt16
	AgricultureScore                   sql.NullInt16
	NutritionScienceScore              sql.NullInt16
	SleepScienceScore                  sql.NullInt16
	ProductivityScore                  sql.NullInt16
	LeadershipScore                    sql.NullInt16
	InternationalRelationsScore        sql.NullInt16
	FuturePredictionsScore             sql.NullInt16
	EventsScore                        sql.NullInt16
	CommunityScore                     sql.NullInt16
	TrendsScore                        sql.NullInt16
	LifestyleScore                     sql.NullInt16
	SoftwareDevelopmentScore           sql.NullInt16
	ProgrammingLanguagesScore          sql.NullInt16
	WebDevelopmentScore                sql.NullInt16
	MobileAppDevelopmentScore          sql.NullInt16
	DebuggingTechniquesScore           sql.NullInt16
	AlgorithmsMathematicsScore         sql.NullInt16
	DatabaseDesignScore                sql.NullInt16
	CloudComputingScore                sql.NullInt16
	ServerManagementScore              sql.NullInt16
	NetworkSecurityScore               sql.NullInt16
	CryptographyScore                  sql.NullInt16
	ArtificialIntelligenceScore        sql.NullInt16
	MachineLearningScore               sql.NullInt16
	DeepLearningScore                  sql.NullInt16
	ComputerVisionScore                sql.NullInt16
	NaturalLanguageProcessingScore     sql.NullInt16
	BlockchainTechnologyScore          sql.NullInt16
	QuantumComputingScore              sql.NullInt16
	EdgeComputingScore                 sql.NullInt16
	MicroservicesArchitectureScore     sql.NullInt16
	DevopsScore                        sql.NullInt16
	ContainerTechnologyScore           sql.NullInt16
	CiCdScore                          sql.NullInt16
	TestAutomationScore                sql.NullInt16
	UxUiDesignScore                    sql.NullInt16
	AgileDevelopmentMethodologiesScore sql.NullInt16
	OpenSourceScore                    sql.NullInt16
	VersionControlScore                sql.NullInt16
	ApiDesignScore                     sql.NullInt16
	PerformanceOptimizationScore       sql.NullInt16
}

type Label struct {
	TweetID   int64
	Label1    NullTweetLabel
	Label2    NullTweetLabel
	Label3    NullTweetLabel
	CreatedAt time.Time
}

type Like struct {
	LikingAccountID string
	OriginalTweetID int64
	CreatedAt       time.Time
}

type Message struct {
	ID              int64
	ConversationID  int64
	SenderAccountID string
	Content         string
	IsRead          bool
	CreatedAt       time.Time
}

type Notification struct {
	ID                 int64
	SenderAccountID    sql.NullString
	RecipientAccountID string
	Type               NotificationType
	Content            sql.NullString
	TweetID            sql.NullInt64
	IsRead             bool
	CreatedAt          time.Time
}

type Profile struct {
	AccountID       string
	Bio             sql.NullString
	ProfileImageUrl sql.NullString
	BannerImageUrl  sql.NullString
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Reply struct {
	ReplyID           int64
	ParentReplyID     sql.NullInt64
	ReplyingAccountID string
	CreatedAt         time.Time
}

type Report struct {
	ID                int64
	ReporterAccountID string
	ReportedAccountID string
	Reason            ReportReason
	Content           sql.NullString
	CreatedAt         time.Time
}

type RetweetsAndQuote struct {
	TweetID             int64
	RetweetingAccountID string
	OriginalTweetID     int64
	CreatedAt           time.Time
}

type Setting struct {
	AccountID string
	IsPrivate sql.NullBool
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Tweet struct {
	ID              int64
	AccountID       string
	IsPinned        bool
	Content         sql.NullString
	Code            sql.NullString
	LikesCount      int32
	RepliesCount    int32
	RetweetsCount   int32
	IsRetweet       bool
	IsReply         bool
	IsQuote         bool
	OriginalTweetID sql.NullInt64
	EngagementScore int32
	Media           pqtype.NullRawMessage
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type TweetHashtag struct {
	TweetID   int64
	HashtagID int64
}
