// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: quotes.sql

package sqlcgen

import (
	"context"
)

const createQuote = `-- name: CreateQuote :exec
INSERT INTO quotes (quote_id, quoting_account_id, original_tweet_id)
VALUES ($1, $2, $3)
`

type CreateQuoteParams struct {
	QuoteID          int64
	QuotingAccountID string
	OriginalTweetID  int64
}

func (q *Queries) CreateQuote(ctx context.Context, arg CreateQuoteParams) error {
	_, err := q.db.ExecContext(ctx, createQuote, arg.QuoteID, arg.QuotingAccountID, arg.OriginalTweetID)
	return err
}
