// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: retweets.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createRetweet = `-- name: CreateRetweet :exec
INSERT INTO retweets (retweeting_account_id, original_tweet_id)
VALUES ($1, $2)
`

type CreateRetweetParams struct {
	RetweetingAccountID string
	OriginalTweetID     int64
}

func (q *Queries) CreateRetweet(ctx context.Context, arg CreateRetweetParams) error {
	_, err := q.db.ExecContext(ctx, createRetweet, arg.RetweetingAccountID, arg.OriginalTweetID)
	return err
}

const deleteRetweet = `-- name: DeleteRetweet :execresult
DELETE FROM retweets
WHERE retweeting_account_id = $1 AND original_tweet_id = $2
`

type DeleteRetweetParams struct {
	RetweetingAccountID string
	OriginalTweetID     int64
}

func (q *Queries) DeleteRetweet(ctx context.Context, arg DeleteRetweetParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteRetweet, arg.RetweetingAccountID, arg.OriginalTweetID)
}
