// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tweets.sql

package sqlcgen

import (
	"context"
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

const createTweet = `-- name: CreateTweet :one
INSERT INTO tweets (
    account_id, content, code, media
) VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateTweetParams struct {
	AccountID string
	Content   sql.NullString
	Code      sql.NullString
	Media     pqtype.NullRawMessage
}

func (q *Queries) CreateTweet(ctx context.Context, arg CreateTweetParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createTweet,
		arg.AccountID,
		arg.Content,
		arg.Code,
		arg.Media,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createTweetAsQuote = `-- name: CreateTweetAsQuote :one
INSERT INTO tweets (
    account_id, is_quote, content, code, media
) VALUES ($1, TRUE, $2, $3, $4)
RETURNING id
`

type CreateTweetAsQuoteParams struct {
	AccountID string
	Content   sql.NullString
	Code      sql.NullString
	Media     pqtype.NullRawMessage
}

func (q *Queries) CreateTweetAsQuote(ctx context.Context, arg CreateTweetAsQuoteParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createTweetAsQuote,
		arg.AccountID,
		arg.Content,
		arg.Code,
		arg.Media,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createTweetAsReply = `-- name: CreateTweetAsReply :one
INSERT INTO tweets (
    account_id, is_reply, content, code, media
) VALUES ($1, TRUE, $2, $3, $4)
RETURNING id
`

type CreateTweetAsReplyParams struct {
	AccountID string
	Content   sql.NullString
	Code      sql.NullString
	Media     pqtype.NullRawMessage
}

func (q *Queries) CreateTweetAsReply(ctx context.Context, arg CreateTweetAsReplyParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createTweetAsReply,
		arg.AccountID,
		arg.Content,
		arg.Code,
		arg.Media,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteTweet = `-- name: DeleteTweet :exec
DELETE FROM tweets WHERE id = $1 AND account_id = $2
`

type DeleteTweetParams struct {
	ID        int64
	AccountID string
}

func (q *Queries) DeleteTweet(ctx context.Context, arg DeleteTweetParams) error {
	_, err := q.db.ExecContext(ctx, deleteTweet, arg.ID, arg.AccountID)
	return err
}

const getAccountIDByTweetID = `-- name: GetAccountIDByTweetID :one
SELECT account_id FROM tweets WHERE id = $1
`

func (q *Queries) GetAccountIDByTweetID(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getAccountIDByTweetID, id)
	var account_id string
	err := row.Scan(&account_id)
	return account_id, err
}

const getPinnedTweetForAccount = `-- name: GetPinnedTweetForAccount :one
SELECT id, account_id, is_pinned, content, code, likes_count, replies_count, retweets_count, is_reply, is_quote, media, created_at, updated_at FROM tweets
WHERE account_id = $1 AND is_pinned = TRUE
LIMIT 1
`

func (q *Queries) GetPinnedTweetForAccount(ctx context.Context, accountID string) (Tweet, error) {
	row := q.db.QueryRowContext(ctx, getPinnedTweetForAccount, accountID)
	var i Tweet
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.IsPinned,
		&i.Content,
		&i.Code,
		&i.LikesCount,
		&i.RepliesCount,
		&i.RetweetsCount,
		&i.IsReply,
		&i.IsQuote,
		&i.Media,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTweetCountByAccountID = `-- name: GetTweetCountByAccountID :one
SELECT COUNT(*) FROM tweets WHERE account_id = $1
`

func (q *Queries) GetTweetCountByAccountID(ctx context.Context, accountID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTweetCountByAccountID, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTweetsByAccountID = `-- name: GetTweetsByAccountID :many
SELECT id, account_id, is_pinned, content, code, likes_count, replies_count, retweets_count, is_reply, is_quote, media, created_at, updated_at FROM tweets
WHERE account_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetTweetsByAccountIDParams struct {
	AccountID string
	Limit     int32
	Offset    int32
}

func (q *Queries) GetTweetsByAccountID(ctx context.Context, arg GetTweetsByAccountIDParams) ([]Tweet, error) {
	rows, err := q.db.QueryContext(ctx, getTweetsByAccountID, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tweet
	for rows.Next() {
		var i Tweet
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.IsPinned,
			&i.Content,
			&i.Code,
			&i.LikesCount,
			&i.RepliesCount,
			&i.RetweetsCount,
			&i.IsReply,
			&i.IsQuote,
			&i.Media,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTweets = `-- name: SearchTweets :many
SELECT id, account_id, is_pinned, content, code, likes_count, replies_count, retweets_count, is_reply, is_quote, media, created_at, updated_at FROM tweets
WHERE content LIKE $1 OR code LIKE $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type SearchTweetsParams struct {
	Content sql.NullString
	Code    sql.NullString
	Limit   int32
	Offset  int32
}

func (q *Queries) SearchTweets(ctx context.Context, arg SearchTweetsParams) ([]Tweet, error) {
	rows, err := q.db.QueryContext(ctx, searchTweets,
		arg.Content,
		arg.Code,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tweet
	for rows.Next() {
		var i Tweet
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.IsPinned,
			&i.Content,
			&i.Code,
			&i.LikesCount,
			&i.RepliesCount,
			&i.RetweetsCount,
			&i.IsReply,
			&i.IsQuote,
			&i.Media,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTweetAsPinned = `-- name: SetTweetAsPinned :exec
UPDATE tweets
SET is_pinned = TRUE
WHERE id = $1 AND account_id = $2
`

type SetTweetAsPinnedParams struct {
	ID        int64
	AccountID string
}

func (q *Queries) SetTweetAsPinned(ctx context.Context, arg SetTweetAsPinnedParams) error {
	_, err := q.db.ExecContext(ctx, setTweetAsPinned, arg.ID, arg.AccountID)
	return err
}

const unpinTweet = `-- name: UnpinTweet :exec
UPDATE tweets
SET is_pinned = FALSE
WHERE id = $1 AND account_id = $2
`

type UnpinTweetParams struct {
	ID        int64
	AccountID string
}

func (q *Queries) UnpinTweet(ctx context.Context, arg UnpinTweetParams) error {
	_, err := q.db.ExecContext(ctx, unpinTweet, arg.ID, arg.AccountID)
	return err
}

const updateTweetCode = `-- name: UpdateTweetCode :exec
UPDATE tweets
SET code = $1
WHERE id = $2 AND account_id = $3
`

type UpdateTweetCodeParams struct {
	Code      sql.NullString
	ID        int64
	AccountID string
}

func (q *Queries) UpdateTweetCode(ctx context.Context, arg UpdateTweetCodeParams) error {
	_, err := q.db.ExecContext(ctx, updateTweetCode, arg.Code, arg.ID, arg.AccountID)
	return err
}

const updateTweetContent = `-- name: UpdateTweetContent :exec
UPDATE tweets
SET content = $1
WHERE id = $2 AND account_id = $3
`

type UpdateTweetContentParams struct {
	Content   sql.NullString
	ID        int64
	AccountID string
}

func (q *Queries) UpdateTweetContent(ctx context.Context, arg UpdateTweetContentParams) error {
	_, err := q.db.ExecContext(ctx, updateTweetContent, arg.Content, arg.ID, arg.AccountID)
	return err
}
