openapi: 3.0.0
info:
    title: Conversation Management API
    version: 1.0.0
    description: API for managing user conversations

paths:
    /conversations:
        get:
            summary: Get conversations of a user
            operationId: GetConversations
            parameters:
                - name: limit
                  in: query
                  schema:
                      type: integer
                      format: int32
                  required: true
                - name: offset
                  in: query
                  schema:
                      type: integer
                      format: int32
                  required: true
            responses:
                "200":
                    description: Conversations retrieved successfully
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ConversationResponses"
                "400":
                    description: Bad request
                "500":
                    description: Internal server error

    /conversations/unread/count:
        get:
            summary: Get unread conversation count of a user
            operationId: GetUnreadConversationCount
            responses:
                "200":
                    description: Unread conversation count retrieved successfully
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/UnreadConversationCountResponse"
                "400":
                    description: Bad request
                "500":
                    description: Internal server error

    /conversations/{user_id}/messages:
        get:
            summary: Get messages of a user
            operationId: GetMessages
            parameters:
                - name: user_id
                  in: path
                  required: true
                  schema:
                      type: string
                - name: limit
                  in: query
                  schema:
                      type: integer
                      format: int32
                  required: true
                - name: offset
                  in: query
                  schema:
                      type: integer
                      format: int32
                  required: true
            responses:
                "200":
                    description: Messages retrieved successfully
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/MessageResponses"
                "400":
                    description: Bad request
                "500":
                    description: Internal server error
        post:
            summary: Send a message to a user
            operationId: SendMessage
            parameters:
                - name: user_id
                  in: path
                  required: true
                  schema:
                      type: string
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/MessageRequest"
            responses:
                "200":
                    description: Message sent successfully
                "400":
                    description: Bad request
                "500":
                    description: Internal server error

    /conversations/{user_id}/messages/read:
        patch:
            summary: Mark messages as read
            operationId: MarkMessagesAsRead
            parameters:
                - name: user_id
                  in: path
                  required: true
                  schema:
                      type: string
            responses:
                "200":
                    description: Messages marked as read successfully
                "400":
                    description: Bad request
                "500":
                    description: Internal server error

components:
    schemas:
        Conversation:
            type: object
            properties:
                id:
                    type: integer
                    format: int64
                opponent_info:
                    $ref: "#/components/schemas/UserInfoWithoutBio"
                last_message_time:
                    type: string
                    format: date-time
                content:
                    type: string
                sender_user_id:
                    type: string
                is_read:
                    type: boolean
            required:
                - id
                - opponent_info
                - last_message_time
                - content
                - sender_user_id
                - is_read
        ConversationResponses:
            type: object
            properties:
                conversations:
                    type: array
                    items:
                        $ref: "#/components/schemas/Conversation"
        UnreadConversationCountResponse:
            type: object
            properties:
                count:
                    type: integer
                    format: int64
            required:
                - count
        MessageRequest:
            type: object
            required:
                - content
            properties:
                content:
                    type: string
        MessageResponse:
            type: object
            required:
                - sender_account_id
                - content
                - is_read
                - created_at
            properties:
                sender_account_id:
                    type: string
                content:
                    type: string
                is_read:
                    type: boolean
                created_at:
                    type: string
                    format: date-time
        MessageResponses:
            type: array
            items:
                $ref: "#/components/schemas/MessageResponse"
        UserInfoWithoutBio:
            type: object
            properties:
                user_id:
                    type: string
                user_name:
                    type: string
                profile_image_url:
                    type: string
                    format: uri
                is_private:
                    type: boolean
                is_admin:
                    type: boolean
            required:
                - user_id
                - user_name
                - profile_image_url
                - is_private
                - is_admin
