openapi: 3.0.0
info:
    title: Tweet Management API
    version: 1.0.0
    description: API for managing tweets

paths:
    /tweets:
        post:
            summary: Create a tweet
            operationId: PostTweet
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/PostTweetRequest"
            responses:
                "201":
                    description: Tweet created successfully
                "400":
                    description: Bad request
                "500":
                    description: Internal server error

    /tweets/{tweet_id}:
        delete:
            summary: Delete a tweet
            operationId: DeleteTweet
            parameters:
                - name: tweet_id
                  in: path
                  required: true
                  schema:
                      type: integer
                      format: int64
            responses:
                "200":
                    description: Tweet deleted successfully
                "400":
                    description: Bad request
                "500":
                    description: Internal server error

    /tweets/{tweet_id}/replies:
        get:
            summary: Get replies for a tweet
            operationId: GetReplyTweetInfos
            parameters:
                - name: tweet_id
                  in: path
                  required: true
                  schema:
                      type: integer
                      format: int64
                - name: limit
                  in: query
                  required: true
                  schema:
                      type: integer
                      format: int32
                - name: offset
                  in: query
                  required: true
                  schema:
                      type: integer
                      format: int32
            responses:
                "200":
                    description: Replies fetched successfully
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: "#/components/schemas/TweetInfo"
                "400":
                    description: Bad request
                "500":
                    description: Internal server error

    /tweets/{tweet_id}/like:
        post:
            summary: Like a tweet and notify poster
            operationId: LikeTweetAndNotify
            parameters:
                - name: tweet_id
                  in: path
                  required: true
                  schema:
                      type: integer
                      format: int64
            responses:
                "200":
                    description: Tweet liked successfully
                "400":
                    description: Bad request
                "500":
                    description: Internal server error
        delete:
            summary: Unlike a tweet
            operationId: UnlikeTweet
            parameters:
                - name: tweet_id
                  in: path
                  required: true
                  schema:
                      type: integer
                      format: int64
            responses:
                "200":
                    description: Tweet unliked successfully
                "400":
                    description: Bad request
                "500":
                    description: Internal server error

    /tweets/{tweet_id}/retweet:
        post:
            summary: Retweet and notify poster
            operationId: RetweetAndNotify
            parameters:
                - name: tweet_id
                  in: path
                  required: true
                  schema:
                      type: integer
                      format: int64
            responses:
                "200":
                    description: Retweet successful
                "400":
                    description: Bad request
                "500":
                    description: Internal server error
        delete:
            summary: Delete retweet
            operationId: Unretweet
            parameters:
                - name: tweet_id
                  in: path
                  required: true
                  schema:
                      type: integer
                      format: int64
            responses:
                "200":
                    description: Retweet deleted successfully
                "400":
                    description: Bad request
                "500":
                    description: Internal server error

    /tweets/{tweet_id}/quote:
        post:
            summary: Quote retweet and notify poster
            operationId: PostQuoteAndNotify
            parameters:
                - name: tweet_id
                  in: path
                  required: true
                  schema:
                      type: integer
                      format: int64
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/PostTweetRequest"
            responses:
                "201":
                    description: Quote retweet successful
                "400":
                    description: Bad request
                "500":
                    description: Internal server error

    /tweets/{tweet_id}/reply:
        post:
            summary: Reply to a tweet
            operationId: PostReplyAndNotify
            parameters:
                - name: tweet_id
                  in: path
                  required: true
                  schema:
                      type: integer
                      format: int64
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/PostTweetRequest"
            responses:
                "201":
                    description: Reply created successfully
                "400":
                    description: Bad request
                "500":
                    description: Internal server error

    /tweets/{tweet_id}/retweets:
        get:
            summary: Get retweets for a tweet
            operationId: GetRetweetingUserInfos
            parameters:
                - name: tweet_id
                  in: path
                  required: true
                  schema:
                      type: integer
                      format: int64
                - name: limit
                  in: query
                  required: true
                  schema:
                      type: integer
                      format: int32
                - name: offset
                  in: query
                  required: true
                  schema:
                      type: integer
                      format: int32
            responses:
                "200":
                    description: Retweets fetched successfully
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: "#/components/schemas/UserInfoWithoutBios"
                "400":
                    description: Bad request
                "500":
                    description: Internal server error

    /tweets/{tweet_id}/likes:
        get:
            summary: Get likes for a tweet
            operationId: GetLikingUserInfos
            parameters:
                - name: tweet_id
                  in: path
                  required: true
                  schema:
                      type: integer
                      format: int64
                - name: limit
                  in: query
                  required: true
                  schema:
                      type: integer
                      format: int32
                - name: offset
                  in: query
                  required: true
                  schema:
                      type: integer
                      format: int32
            responses:
                "200":
                    description: Likes fetched successfully
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: "#/components/schemas/UserInfoWithoutBios"
                "400":
                    description: Bad request
                "500":
                    description: Internal server error

    /tweets/{tweet_id}/quotes:
        get:
            summary: Get quotes for a tweet
            operationId: GetQuotingUserInfos
            parameters:
                - name: tweet_id
                  in: path
                  required: true
                  schema:
                      type: integer
                      format: int64
                - name: limit
                  in: query
                  required: true
                  schema:
                      type: integer
                      format: int32
                - name: offset
                  in: query
                  required: true
                  schema:
                      type: integer
                      format: int32
            responses:
                "200":
                    description: Quotes fetched successfully
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: "#/components/schemas/UserInfoWithoutBios"
                "400":
                    description: Bad request
                "500":
                    description: Internal server error

    /tweets/timeline:
        get:
            summary: Get timeline for user
            operationId: GetTimelineTweetInfos
            parameters:
                - name: limit
                  in: query
                  required: true
                  schema:
                      type: integer
                      format: int32
                - name: offset
                  in: query
                  required: true
                  schema:
                      type: integer
                      format: int32
            responses:
                "200":
                    description: Timeline fetched successfully
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: "#/components/schemas/GetTimelineTweetInfos"
                "400":
                    description: Bad request
                "500":
                    description: Internal server error

components:
    schemas:
        PostTweetRequest:
            type: object
            properties:
                content:
                    type: string
                code:
                    type: string
                media:
                    $ref: "#/components/schemas/Media"
        GetTimelineTweetInfos:
            type: array
            items:
                $ref: "#/components/schemas/GetTimelineTweetInfo"
        GetTimelineTweetInfo:
            type: object
            properties:
                Tweet:
                    $ref: "#/components/schemas/TweetInfo"
                OriginalTweet:
                    $ref: "#/components/schemas/TweetInfo"
                    nullable: true
                ParentReply:
                    $ref: "#/components/schemas/TweetInfo"
                    nullable: true
                OmittedReplyExist:
                    type: boolean
                    nullable: true
            required:
                - Tweet
        TweetInfos:
            type: array
            items:
                $ref: "#/components/schemas/TweetInfo"
        TweetInfo:
            type: object
            properties:
                TweetID:
                    type: integer
                    format: int64
                UserInfo:
                    $ref: "#/components/schemas/UserInfoWithoutBio"
                Content:
                    type: string
                    nullable: true
                Code:
                    type: string
                    nullable: true
                Media:
                    $ref: "#/components/schemas/Media"
                    nullable: true
                LikesCount:
                    type: integer
                    format: int32
                RetweetsCount:
                    type: integer
                    format: int32
                RepliesCount:
                    type: integer
                    format: int32
                IsQuote:
                    type: boolean
                IsReply:
                    type: boolean
                IsPinned:
                    type: boolean
                HasLiked:
                    type: boolean
                HasRetweeted:
                    type: boolean
                CreatedAt:
                    type: string
                    format: date-time
            required:
                - TweetID
                - UserInfo
                - LikesCount
                - RetweetsCount
                - RepliesCount
                - IsQuote
                - IsReply
                - IsPinned
                - HasLiked
                - HasRetweeted
                - CreatedAt
        Media:
            type: object
            properties:
                type:
                    type: string
                url:
                    type: string
            required:
                - type
                - url
        UserInfoWithoutBio:
            type: object
            properties:
                user_id:
                    type: string
                    description: The ID of the user.
                user_name:
                    type: string
                    description: The name of the user.
                profile_image_url:
                    type: string
                    format: uri
                    description: URL of the user's profile image.
            required:
                - user_id
                - user_name
                - profile_image_url
        UserInfoWithoutBios:
            type: array
            items:
                $ref: "#/components/schemas/UserInfoWithoutBio"
