openapi: 3.0.0
info:
    title: Tweet Management API
    version: 1.0.0
    description: API for managing tweets

paths:
    /tweets:
        post:
            summary: Create a tweet
            operationId: PostTweet
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/PostTweetRequest"
            responses:
                "201":
                    description: Tweet created successfully
                "400":
                    description: Bad request
                "500":
                    description: Internal server error

    /tweets/{tweet_id}/like:
        post:
            summary: Like a tweet and notify poster
            operationId: LikeTweetAndNotify
            parameters:
                - name: tweet_id
                  in: path
                  required: true
                  schema:
                      type: integer
                      format: int64
            responses:
                "200":
                    description: Tweet liked successfully
                "400":
                    description: Bad request
                "500":
                    description: Internal server error
        delete:
            summary: Unlike a tweet
            operationId: UnlikeTweet
            parameters:
                - name: tweet_id
                  in: path
                  required: true
                  schema:
                      type: integer
                      format: int64
            responses:
                "200":
                    description: Tweet unliked successfully
                "400":
                    description: Bad request
                "500":
                    description: Internal server error

    /tweets/{tweet_id}/retweet:
        post:
            summary: Retweet and notify poster
            operationId: RetweetAndNotify
            parameters:
                - name: tweet_id
                  in: path
                  required: true
                  schema:
                      type: integer
                      format: int64
            responses:
                "200":
                    description: Retweet successful
                "400":
                    description: Bad request
                "500":
                    description: Internal server error
        delete:
            summary: Delete retweet
            operationId: Unretweet
            parameters:
                - name: tweet_id
                  in: path
                  required: true
                  schema:
                      type: integer
                      format: int64
            responses:
                "200":
                    description: Retweet deleted successfully
                "400":
                    description: Bad request
                "500":
                    description: Internal server error

    /tweets/{tweet_id}/reply:
        post:
            summary: Reply to a tweet
            operationId: ReplyTweetAndNotify
            parameters:
                - name: tweet_id
                  in: path
                  required: true
                  schema:
                      type: integer
                      format: int64
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/PostTweetRequest"
            responses:
                "201":
                    description: Reply created successfully
                "400":
                    description: Bad request
                "500":
                    description: Internal server error

components:
    schemas:
        PostTweetRequest:
            type: object
            properties:
                content:
                    type: string
                code:
                    type: string
                media:
                    $ref: "#/components/schemas/Media"
        Media:
            type: object
            properties:
                type:
                    type: string
                url:
                    type: string
            required:
                - type
                - url
