openapi: 3.0.0
info:
    title: Sidebar API
    version: 1.0.0
    description: API for managing sidebar content

paths:
    /sidebar:
        get:
            summary: Get sidebar information
            operationId: GetSidebarInfo
            responses:
                "200":
                    description: Sidebar content retrieved successfully
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/SidebarInfo"
                "400":
                    description: Bad request
                "500":
                    description: Internal server error

components:
    schemas:
        SidebarInfo:
            type: object
            properties:
                user_info:
                    $ref: "#/components/schemas/UserInfoWithoutBio"
                unread_conversation_count:
                    type: integer
                    format: int64
                unread_notification_count:
                    type: integer
                    format: int64
            required:
                - user_info
                - unread_conversation_count
                - unread_notification_count
        UserInfoWithoutBio:
            type: object
            properties:
                user_id:
                    type: string
                user_name:
                    type: string
                profile_image_url:
                    type: string
                    format: uri
                is_private:
                    type: boolean
                is_admin:
                    type: boolean
            required:
                - user_id
                - user_name
                - profile_image_url
                - is_private
                - is_admin
