// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: blocks.sql

package sqlc

import (
	"context"
)

const checkBlockExists = `-- name: CheckBlockExists :one
SELECT EXISTS(
    SELECT 1 FROM blocks
    WHERE blocker_account_id = ? AND blocked_account_id = ?
) AS is_blocked
`

type CheckBlockExistsParams struct {
	BlockerAccountID string
	BlockedAccountID string
}

func (q *Queries) CheckBlockExists(ctx context.Context, arg CheckBlockExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkBlockExists, arg.BlockerAccountID, arg.BlockedAccountID)
	var is_blocked bool
	err := row.Scan(&is_blocked)
	return is_blocked, err
}

const createBlock = `-- name: CreateBlock :exec
INSERT INTO blocks (blocker_account_id, blocked_account_id)
VALUES (?, ?)
`

type CreateBlockParams struct {
	BlockerAccountID string
	BlockedAccountID string
}

func (q *Queries) CreateBlock(ctx context.Context, arg CreateBlockParams) error {
	_, err := q.db.ExecContext(ctx, createBlock, arg.BlockerAccountID, arg.BlockedAccountID)
	return err
}

const deleteAllBlocksForUser = `-- name: DeleteAllBlocksForUser :exec
DELETE FROM blocks
WHERE blocker_account_id = ? OR blocked_account_id = ?
`

type DeleteAllBlocksForUserParams struct {
	BlockerAccountID string
	BlockedAccountID string
}

func (q *Queries) DeleteAllBlocksForUser(ctx context.Context, arg DeleteAllBlocksForUserParams) error {
	_, err := q.db.ExecContext(ctx, deleteAllBlocksForUser, arg.BlockerAccountID, arg.BlockedAccountID)
	return err
}

const deleteBlock = `-- name: DeleteBlock :exec
DELETE FROM blocks
WHERE blocker_account_id = ? AND blocked_account_id = ?
`

type DeleteBlockParams struct {
	BlockerAccountID string
	BlockedAccountID string
}

func (q *Queries) DeleteBlock(ctx context.Context, arg DeleteBlockParams) error {
	_, err := q.db.ExecContext(ctx, deleteBlock, arg.BlockerAccountID, arg.BlockedAccountID)
	return err
}

const getBlockCount = `-- name: GetBlockCount :one
SELECT COUNT(*) FROM blocks
WHERE blocker_account_id = ?
`

func (q *Queries) GetBlockCount(ctx context.Context, blockerAccountID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getBlockCount, blockerAccountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getBlockedByCount = `-- name: GetBlockedByCount :one
SELECT COUNT(*) FROM blocks
WHERE blocked_account_id = ?
`

func (q *Queries) GetBlockedByCount(ctx context.Context, blockedAccountID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getBlockedByCount, blockedAccountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getBlockedUsers = `-- name: GetBlockedUsers :many
SELECT blocked_account_id
FROM blocks
WHERE blocker_account_id = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type GetBlockedUsersParams struct {
	BlockerAccountID string
	Limit            int32
	Offset           int32
}

func (q *Queries) GetBlockedUsers(ctx context.Context, arg GetBlockedUsersParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getBlockedUsers, arg.BlockerAccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var blocked_account_id string
		if err := rows.Scan(&blocked_account_id); err != nil {
			return nil, err
		}
		items = append(items, blocked_account_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBlockersOfUser = `-- name: GetBlockersOfUser :many
SELECT blocker_account_id
FROM blocks
WHERE blocked_account_id = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type GetBlockersOfUserParams struct {
	BlockedAccountID string
	Limit            int32
	Offset           int32
}

func (q *Queries) GetBlockersOfUser(ctx context.Context, arg GetBlockersOfUserParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getBlockersOfUser, arg.BlockedAccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var blocker_account_id string
		if err := rows.Scan(&blocker_account_id); err != nil {
			return nil, err
		}
		items = append(items, blocker_account_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
