services:
    hackathon_postgres:
        container_name: hackathon_postgres
        build:
            context: .
            dockerfile: Dockerfile
        platform: linux/x86_64
        tty: true
        ports:
            - "3306:3306"
        env_file:
            - .env
        volumes:
            - type: volume
              source: hackathon_postgres
              target: /var/lib/mysql
            - type: bind
              source: ./init
              target: /docker-entrypoint-initdb.d

volumes:
    hackathon_postgres:
        name: hackathon_postgres
