openapi: 3.0.0
info:
    title: Execute API
    version: 1.0.0
    description: API for executing source code

paths:
    /execute:
        post:
            summary: Execute source code
            operationId: ExecuteCode
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/ExecuteRequest"
            responses:
                "200":
                    description: Source code executed successfully
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ExecuteResponse"
                "400":
                    description: Bad request
                "500":
                    description: Internal server error

components:
    schemas:
        ExecuteRequest:
            type: object
            $ref: "#/components/schemas/Code"
        ExecuteResponse:
            type: object
            properties:
                status:
                    type: string
                output:
                    type: string
                message:
                    type: string
            required:
                - status
        Code:
            type: object
            properties:
                content:
                    type: string
                language:
                    type: string
            required:
                - content
                - language
