openapi: 3.0.0
info:
    title: Profile Management API
    version: 1.0.0
    description: API for managing profiles

paths:
    /profiles:
        patch:
            summary: Update profiles
            operationId: UpdateProfiles
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/UpdateProfilesRequest"
            responses:
                "200":
                    description: Profiles updated successfully
                "400":
                    description: Bad request
                "500":
                    description: Internal server error

components:
    schemas:
        UpdateProfilesRequest:
            type: object
            properties:
                user_id:
                    type: string
                    nullable: true
                user_name:
                    type: string
                    nullable: true
                bio:
                    type: string
                    nullable: true
                profile_image_url:
                    type: string
                    format: uri
                    nullable: true
                banner_image_url:
                    type: string
                    format: uri
                    nullable: true
