CREATE TABLE accounts (
    id CHAR(28) PRIMARY KEY,
    user_id VARCHAR(28) UNIQUE NOT NULL,
    user_name VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_accounts_user_name (user_name)
);