firebase:
    type: ${FIREBASE_TYPE}
    project_id: ${FIREBASE_PROJECT_ID}
    private_key_id: ${FIREBASE_PRIVATE_KEY_ID}
    private_key: ${FIREBASE_PRIVATE_KEY}
    client_email: ${FIREBASE_CLIENT_EMAIL}
    client_id: ${FIREBASE_CLIENT_ID}
    auth_uri: https://accounts.google.com/o/oauth2/auth
    token_uri: https://oauth2.googleapis.com/token
    auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
    client_x509_cert_url: ${FIREBASE_CLIENT_X509_CERT_URL}
    universe_domain: gogoleapis.com
db:
    driver: mysql
    user: user
    password: ${DB_PASSWORD}
    host: localhost:3306
    database: mydatabase
