name: Go

on:
    push:
        paths:
            - "production/**/*.go"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.23"

            - name: Test
              run: cd production && go test -v ./...
