// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlcgen

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type FollowStatus string

const (
	FollowStatusAccepted FollowStatus = "accepted"
	FollowStatusPending  FollowStatus = "pending"
)

func (e *FollowStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FollowStatus(s)
	case string:
		*e = FollowStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for FollowStatus: %T", src)
	}
	return nil
}

type NullFollowStatus struct {
	FollowStatus FollowStatus
	Valid        bool // Valid is true if FollowStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFollowStatus) Scan(value interface{}) error {
	if value == nil {
		ns.FollowStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FollowStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFollowStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FollowStatus), nil
}

type NotificationType string

const (
	NotificationTypeFollow          NotificationType = "follow"
	NotificationTypeLike            NotificationType = "like"
	NotificationTypeRetweet         NotificationType = "retweet"
	NotificationTypeReply           NotificationType = "reply"
	NotificationTypeMessage         NotificationType = "message"
	NotificationTypeQuote           NotificationType = "quote"
	NotificationTypeFollowRequest   NotificationType = "follow_request"
	NotificationTypeRequestAccepted NotificationType = "request_accepted"
	NotificationTypeReport          NotificationType = "report"
	NotificationTypeWarning         NotificationType = "warning"
	NotificationTypeOther           NotificationType = "other"
)

func (e *NotificationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationType(s)
	case string:
		*e = NotificationType(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationType: %T", src)
	}
	return nil
}

type NullNotificationType struct {
	NotificationType NotificationType
	Valid            bool // Valid is true if NotificationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationType) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationType), nil
}

type ReportReason string

const (
	ReportReasonSpam                 ReportReason = "spam"
	ReportReasonHarassment           ReportReason = "harassment"
	ReportReasonInappropriateContent ReportReason = "inappropriate_content"
	ReportReasonOther                ReportReason = "other"
)

func (e *ReportReason) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReportReason(s)
	case string:
		*e = ReportReason(s)
	default:
		return fmt.Errorf("unsupported scan type for ReportReason: %T", src)
	}
	return nil
}

type NullReportReason struct {
	ReportReason ReportReason
	Valid        bool // Valid is true if ReportReason is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReportReason) Scan(value interface{}) error {
	if value == nil {
		ns.ReportReason, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReportReason.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReportReason) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReportReason), nil
}

type TweetLabel string

const (
	TweetLabelNews                          TweetLabel = "news"
	TweetLabelPolitics                      TweetLabel = "politics"
	TweetLabelEconomics                     TweetLabel = "economics"
	TweetLabelHealth                        TweetLabel = "health"
	TweetLabelSports                        TweetLabel = "sports"
	TweetLabelEntertainment                 TweetLabel = "entertainment"
	TweetLabelArt                           TweetLabel = "art"
	TweetLabelCooking                       TweetLabel = "cooking"
	TweetLabelTravel                        TweetLabel = "travel"
	TweetLabelFashion                       TweetLabel = "fashion"
	TweetLabelBeauty                        TweetLabel = "beauty"
	TweetLabelPets                          TweetLabel = "pets"
	TweetLabelParenting                     TweetLabel = "parenting"
	TweetLabelEducation                     TweetLabel = "education"
	TweetLabelEnvironment                   TweetLabel = "environment"
	TweetLabelClimate                       TweetLabel = "climate"
	TweetLabelSpace                         TweetLabel = "space"
	TweetLabelMentalHealth                  TweetLabel = "mental_health"
	TweetLabelFitness                       TweetLabel = "fitness"
	TweetLabelReading                       TweetLabel = "reading"
	TweetLabelHistory                       TweetLabel = "history"
	TweetLabelPhilosophy                    TweetLabel = "philosophy"
	TweetLabelReligion                      TweetLabel = "religion"
	TweetLabelCulture                       TweetLabel = "culture"
	TweetLabelVolunteering                  TweetLabel = "volunteering"
	TweetLabelSocialIssues                  TweetLabel = "social_issues"
	TweetLabelLaw                           TweetLabel = "law"
	TweetLabelTaxes                         TweetLabel = "taxes"
	TweetLabelInvestment                    TweetLabel = "investment"
	TweetLabelRealEstate                    TweetLabel = "real_estate"
	TweetLabelDiy                           TweetLabel = "diy"
	TweetLabelGardening                     TweetLabel = "gardening"
	TweetLabelInteriorDesign                TweetLabel = "interior_design"
	TweetLabelAutomotive                    TweetLabel = "automotive"
	TweetLabelGaming                        TweetLabel = "gaming"
	TweetLabelAnimeManga                    TweetLabel = "anime_manga"
	TweetLabelCreativeWorks                 TweetLabel = "creative_works"
	TweetLabelPhotographyVideo              TweetLabel = "photography_video"
	TweetLabelMedia                         TweetLabel = "media"
	TweetLabelMarketing                     TweetLabel = "marketing"
	TweetLabelBranding                      TweetLabel = "branding"
	TweetLabelEntrepreneurship              TweetLabel = "entrepreneurship"
	TweetLabelRemoteWork                    TweetLabel = "remote_work"
	TweetLabelDataScience                   TweetLabel = "data_science"
	TweetLabelIot                           TweetLabel = "iot"
	TweetLabelRoboticsEngineering           TweetLabel = "robotics_engineering"
	TweetLabelBiotechnology                 TweetLabel = "biotechnology"
	TweetLabelNanotechnology                TweetLabel = "nanotechnology"
	TweetLabelEnergyTechnology              TweetLabel = "energy_technology"
	TweetLabelArchaeology                   TweetLabel = "archaeology"
	TweetLabelPsychology                    TweetLabel = "psychology"
	TweetLabelSociology                     TweetLabel = "sociology"
	TweetLabelAnthropology                  TweetLabel = "anthropology"
	TweetLabelGeography                     TweetLabel = "geography"
	TweetLabelGeology                       TweetLabel = "geology"
	TweetLabelMeteorology                   TweetLabel = "meteorology"
	TweetLabelDisasterEmergencyManagement   TweetLabel = "disaster_emergency_management"
	TweetLabelUrbanPlanning                 TweetLabel = "urban_planning"
	TweetLabelArchitecture                  TweetLabel = "architecture"
	TweetLabelAgriculture                   TweetLabel = "agriculture"
	TweetLabelNutritionScience              TweetLabel = "nutrition_science"
	TweetLabelSleepScience                  TweetLabel = "sleep_science"
	TweetLabelProductivity                  TweetLabel = "productivity"
	TweetLabelLeadership                    TweetLabel = "leadership"
	TweetLabelInternationalRelations        TweetLabel = "international_relations"
	TweetLabelFuturePredictions             TweetLabel = "future_predictions"
	TweetLabelEvents                        TweetLabel = "events"
	TweetLabelCommunity                     TweetLabel = "community"
	TweetLabelTrends                        TweetLabel = "trends"
	TweetLabelLifestyle                     TweetLabel = "lifestyle"
	TweetLabelSoftwareDevelopment           TweetLabel = "software_development"
	TweetLabelProgrammingLanguages          TweetLabel = "programming_languages"
	TweetLabelWebDevelopment                TweetLabel = "web_development"
	TweetLabelMobileAppDevelopment          TweetLabel = "mobile_app_development"
	TweetLabelDebuggingTechniques           TweetLabel = "debugging_techniques"
	TweetLabelAlgorithmsMathematics         TweetLabel = "algorithms_mathematics"
	TweetLabelDatabaseDesign                TweetLabel = "database_design"
	TweetLabelCloudComputing                TweetLabel = "cloud_computing"
	TweetLabelServerManagement              TweetLabel = "server_management"
	TweetLabelNetworkSecurity               TweetLabel = "network_security"
	TweetLabelCryptography                  TweetLabel = "cryptography"
	TweetLabelArtificialIntelligence        TweetLabel = "artificial_intelligence"
	TweetLabelMachineLearning               TweetLabel = "machine_learning"
	TweetLabelDeepLearning                  TweetLabel = "deep_learning"
	TweetLabelComputerVision                TweetLabel = "computer_vision"
	TweetLabelNaturalLanguageProcessing     TweetLabel = "natural_language_processing"
	TweetLabelBlockchainTechnology          TweetLabel = "blockchain_technology"
	TweetLabelQuantumComputing              TweetLabel = "quantum_computing"
	TweetLabelEdgeComputing                 TweetLabel = "edge_computing"
	TweetLabelMicroservicesArchitecture     TweetLabel = "microservices_architecture"
	TweetLabelDevops                        TweetLabel = "devops"
	TweetLabelContainerTechnology           TweetLabel = "container_technology"
	TweetLabelCiCd                          TweetLabel = "ci_cd"
	TweetLabelTestAutomation                TweetLabel = "test_automation"
	TweetLabelUxUiDesign                    TweetLabel = "ux_ui_design"
	TweetLabelAgileDevelopmentMethodologies TweetLabel = "agile_development_methodologies"
	TweetLabelOpenSource                    TweetLabel = "open_source"
	TweetLabelVersionControl                TweetLabel = "version_control"
	TweetLabelApiDesign                     TweetLabel = "api_design"
	TweetLabelPerformanceOptimization       TweetLabel = "performance_optimization"
)

func (e *TweetLabel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TweetLabel(s)
	case string:
		*e = TweetLabel(s)
	default:
		return fmt.Errorf("unsupported scan type for TweetLabel: %T", src)
	}
	return nil
}

type NullTweetLabel struct {
	TweetLabel TweetLabel
	Valid      bool // Valid is true if TweetLabel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTweetLabel) Scan(value interface{}) error {
	if value == nil {
		ns.TweetLabel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TweetLabel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTweetLabel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TweetLabel), nil
}

type Account struct {
	ID          string
	UserID      string
	UserName    string
	IsSuspended bool
	IsAdmin     bool
	CreatedAt   time.Time
}

type Block struct {
	BlockerAccountID string
	BlockedAccountID string
	CreatedAt        time.Time
}

type Conversation struct {
	ID              int64
	Account1ID      string
	Account2ID      string
	LastMessageID   sql.NullInt64
	LastMessageTime time.Time
}

type Follow struct {
	FollowerAccountID  string
	FollowingAccountID string
	Status             FollowStatus
	CreatedAt          time.Time
}

type Hashtag struct {
	ID        int64
	Tag       string
	CreatedAt time.Time
}

type Interest struct {
	AccountID                          string
	NewsScore                          int16
	PoliticsScore                      int16
	EconomicsScore                     int16
	HealthScore                        int16
	SportsScore                        int16
	EntertainmentScore                 int16
	ArtScore                           int16
	CookingScore                       int16
	TravelScore                        int16
	FashionScore                       int16
	BeautyScore                        int16
	PetsScore                          int16
	ParentingScore                     int16
	EducationScore                     int16
	EnvironmentScore                   int16
	ClimateScore                       int16
	SpaceScore                         int16
	MentalHealthScore                  int16
	FitnessScore                       int16
	ReadingScore                       int16
	HistoryScore                       int16
	PhilosophyScore                    int16
	ReligionScore                      int16
	CultureScore                       int16
	VolunteeringScore                  int16
	SocialIssuesScore                  int16
	LawScore                           int16
	TaxesScore                         int16
	InvestmentScore                    int16
	RealEstateScore                    int16
	DiyScore                           int16
	GardeningScore                     int16
	InteriorDesignScore                int16
	AutomotiveScore                    int16
	GamingScore                        int16
	AnimeMangaScore                    int16
	CreativeWorksScore                 int16
	PhotographyVideoScore              int16
	MediaScore                         int16
	MarketingScore                     int16
	BrandingScore                      int16
	EntrepreneurshipScore              int16
	RemoteWorkScore                    int16
	DataScienceScore                   int16
	IotScore                           int16
	RoboticsEngineeringScore           int16
	BiotechnologyScore                 int16
	NanotechnologyScore                int16
	EnergyTechnologyScore              int16
	ArchaeologyScore                   int16
	PsychologyScore                    int16
	SociologyScore                     int16
	AnthropologyScore                  int16
	GeographyScore                     int16
	GeologyScore                       int16
	MeteorologyScore                   int16
	DisasterEmergencyManagementScore   int16
	UrbanPlanningScore                 int16
	ArchitectureScore                  int16
	AgricultureScore                   int16
	NutritionScienceScore              int16
	SleepScienceScore                  int16
	ProductivityScore                  int16
	LeadershipScore                    int16
	InternationalRelationsScore        int16
	FuturePredictionsScore             int16
	EventsScore                        int16
	CommunityScore                     int16
	TrendsScore                        int16
	LifestyleScore                     int16
	SoftwareDevelopmentScore           int16
	ProgrammingLanguagesScore          int16
	WebDevelopmentScore                int16
	MobileAppDevelopmentScore          int16
	DebuggingTechniquesScore           int16
	AlgorithmsMathematicsScore         int16
	DatabaseDesignScore                int16
	CloudComputingScore                int16
	ServerManagementScore              int16
	NetworkSecurityScore               int16
	CryptographyScore                  int16
	ArtificialIntelligenceScore        int16
	MachineLearningScore               int16
	DeepLearningScore                  int16
	ComputerVisionScore                int16
	NaturalLanguageProcessingScore     int16
	BlockchainTechnologyScore          int16
	QuantumComputingScore              int16
	EdgeComputingScore                 int16
	MicroservicesArchitectureScore     int16
	DevopsScore                        int16
	ContainerTechnologyScore           int16
	CiCdScore                          int16
	TestAutomationScore                int16
	UxUiDesignScore                    int16
	AgileDevelopmentMethodologiesScore int16
	OpenSourceScore                    int16
	VersionControlScore                int16
	ApiDesignScore                     int16
	PerformanceOptimizationScore       int16
}

type Label struct {
	TweetID   int64
	Label1    NullTweetLabel
	Label2    NullTweetLabel
	Label3    NullTweetLabel
	CreatedAt time.Time
}

type Like struct {
	LikingAccountID string
	OriginalTweetID int64
	CreatedAt       time.Time
}

type Message struct {
	ID              int64
	ConversationID  int64
	SenderAccountID string
	Content         string
	IsRead          bool
	CreatedAt       time.Time
}

type Notification struct {
	ID                 int64
	SenderAccountID    sql.NullString
	RecipientAccountID string
	Type               NotificationType
	Content            sql.NullString
	TweetID            sql.NullInt64
	IsRead             bool
	CreatedAt          time.Time
}

type Profile struct {
	AccountID       string
	Bio             sql.NullString
	ProfileImageUrl sql.NullString
	BannerImageUrl  sql.NullString
	CreatedAt       time.Time
}

type Quote struct {
	QuoteID          int64
	QuotingAccountID string
	OriginalTweetID  int64
	CreatedAt        time.Time
}

type Reply struct {
	ReplyID           int64
	OriginalTweetID   int64
	ParentReplyID     sql.NullInt64
	ReplyingAccountID string
	CreatedAt         time.Time
}

type Report struct {
	ID                int64
	ReporterAccountID string
	ReportedAccountID string
	Reason            ReportReason
	Content           sql.NullString
	CreatedAt         time.Time
}

type Retweet struct {
	RetweetingAccountID string
	OriginalTweetID     int64
	CreatedAt           time.Time
}

type Setting struct {
	AccountID string
	IsPrivate sql.NullBool
	CreatedAt time.Time
}

type Tweet struct {
	ID            int64
	AccountID     string
	IsPinned      bool
	Content       sql.NullString
	Code          pqtype.NullRawMessage
	LikesCount    int32
	RepliesCount  int32
	RetweetsCount int32
	IsReply       bool
	IsQuote       bool
	Media         pqtype.NullRawMessage
	CreatedAt     time.Time
}

type TweetHashtag struct {
	TweetID   int64
	HashtagID int64
}
